### ISSUE TITLE
报CORS错误

### ISSUE THREAD

**Issue by 84896150** [blueju/lowcode-multi-page-demo#4]
![image](https://user-images.githubusercontent.com/3245204/195607674-2c66abbd-ac51-402e-84e9-21a9f162ca70.png)

大佬 ，我用上面的请求做测试。但是一直包错：has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

![image](https://user-images.githubusercontent.com/3245204/195607695-a8412430-59f8-418e-810d-e7858fd104fb.png)
请问下怎么解决呢？

**Comment by blueju** [comment]
这个你应该到 lowcode-engine 那里提问啦。
这个遇到过，基本都是 CORS 没配置好，CORS 配置其实还挺多的，前后端要对应起来，不然就会报这种错误。
你试试换成 apipost，apifox 里的那种 mock 接口，就能请求得通。
